et_ticket:
  pk: id
  fields:
    id: INT NOT NULL AUTO_INCREMENT
    lead_id: INT
    url: VARCHAR(256) NOT NULL
    local_path: VARCHAR(20)
    ticket_type: TINYINT(1)
    cost: FLOAT
    sent_at: INT DEFAULT NULL
    created_at: INT
  form:
    fields:
      lead_id:
        widget: text
        widget_conf:
          required: 0
      url:
        widget: text
        widget_conf:
          required: 1
          size: 256
      local_url:
        widget: text
        widget_conf:
          required: 0
      ticket_type:
        widget: select
        widget_conf:
          required: 1
          options:
            1: "Adult eSaver"
            2: "eMovie"
            3: "Child eSaver"
      cost:
        widget: text
        widget_conf:
          required: 1
      sent_at:
        widget: text
        widget_conf:
          required: 0
      created_at:
        widget: text
        widget_conf:
          required: 0
    names:
      en: ExperienceThis Ticket
      zh: ExperienceThis 电影票

    
lead:
  pk: id
  fields:
    id: INT NOT NULL AUTO_INCREMENT
    email: VARCHAR(128)
    wechat_id: VARCHAR(32)
    ticket_type: TINYINT(1)
    ticket_num: TINYINT
    created_at: INT
    processed: TINYINT(1) DEFAULT 0
    processed_at: INT
  form:
    fields:
      email:
        widget: text
        widget_conf:
          required: 1
      wechat_id:
        widget: text
        widget_conf:
          required: 0
      ticket_type:
        widget: select
        widget_conf:
          required: 1
          options:
            1: "Adult eSaver"
            2: "eMovie"
            3: "Child eSaver"
      ticket_num:
        widget: select
        widget_conf:
          required: 1
          options:
            1: 1
            2: 2
            3: 3
            4: 4
            5: 5
            6: 6
            7: 7
            8: 8
            9: 9
            10: 10
      created_at:
        widget: text
        widget_conf:
          required: 0
      processed:
        widget: checkbox_single
        widget_conf: 
      processed_at:
        widget: text
        widget_conf:
          required: 0
    names:
      en: Lead
      zh: 订单

transaction:
  pk: id
  fields:
    id: INT NOT NULL AUTO_INCREMENT
    ticket_id: INT
    lead_id: INT
    timestamp: INT
    payment: FLOAT
    gross_profit: FLOAT
  fks:
    ticket_id:
      foreign_key: ticket_id
      references: et_ticket.id
      on_delete: CASCADE
      on_update: CASCADE
    lead_id:
      foreign_key: lead_id
      references: lead.id
      on_delete: CASCADE
      on_update: CASCADE
  form:
    fields:
      ticket_id:
        widget: text
        widget_conf:
          required: 0
      lead_id:
        widget: text
        widget_conf:
          required: 0
      timestamp:
        widget: text
        widget_conf:
          required: 0
      payment:
        widget: text
        widget_conf:
          required: 0
      gross_profit:
        widget: text
        widget_conf:
          required: 0
    names:
      en: Transaction
      zh: 交易