ticket_type:
  1:
    name: "成人折扣通票(除周六晚)"
    original_name: "Adult eSaver"
    cost: 10.5
    original_cost: 20
  2:
    name: "成人折扣通票"
    original_name: "eMovie"
    cost: 12.8
    original_cost: 20
  3:
    name: "儿童折扣通票"
    original_name: "Child eSaver"
    cost: 8
    original_cost: 17

payment_type:
  1: stripe
  
experiencethis_account:
  username: "hhlQk9UQt12bj5CbpFWbnBUbvNmLn5Wa2F2c1F2V"
  password: "SRmW==wSDl2b2gTMsR2ZnNWekRET"
  
cc:
  name: "uZXa=MkWktWSBNEIOFUVZ5URIpVN"
  number: "xY3aUBVayZTO5kjNzkzNyUDOxMTNzUDc"
  month: "yZlU==gNM5kVxATM"
  year: "TFEZ==QeTZEU3EzN"
  cvv: "mVzQ=YTRERjM4kTT"

nrma:
  member_id: 9407466

buyer:
  email: ausaving.com@gmail.com
  title: Mr
  firstname: Jeffrey
  lastname: Cai
  address1: 15 Cowper St
  suburb: Parramatta
  state: NSW
  postcode: 2150