ticket_type:
  1:
    name: "成人折扣通票(除周六晚)"
    original_name: "Adult eSaver"
    cost: 10.5
    original_cost: 20
  2:
    name: "成人折扣通票"
    original_name: "eMovie"
    cost: 12.8
    original_cost: 20
  3:
    name: "儿童折扣通票"
    original_name: "Child eSaver"
    cost: 8
    original_cost: 17

payment_type:
  1: stripe