sitename: 澳洲电影票务

wechat_api:
  url: http://ozboxoffice.websitesydney.net/wechat/api
  token: Lh1SkHVt7Dx
  encoding_aes_key: P1JUsQbFX6AL5soFjtODjBkBtTg2xkBMcVAQIpLEs5Z
  appid: wxc24050ffd4090eeb
  appsecret: 9af98275771cf61c2a6c8f38cc804991