sitename: 澳洲电影票务

wechat_api:
  url: http://ozboxoffice.websitesydney.net/wechat/api
  token: Lh1SkHVt7Dx
  encoding_aes_key: P1JUsQbFX6AL5soFjtODjBkBtTg2xkBMcVAQIpLEs5Z
  appid: wxc24050ffd4090eeb
  appsecret: 9af98275771cf61c2a6c8f38cc804991
  
  
stripe:
  test_secret_key: yhjN==AO5IXYwlGcwpXZUlkNGV1MMJlW1YUa3xUZwxUWfR3clR3XrNHR
  test_publishable_key: ZNkS==QZRdWQl92ZTBnZwEDc2UHdCJTYxZkQYZGc0YVWfR3clR3XrBnc
  live_secret_key: UF2Y==wYMlmbW1UdFhDboNXUO5Ga6xWb2EEOwBHR5dFRfVmdpx2XrNHa
  live_publishable_key: 1Qzb==gcvF3c5UDSORjc5FTatRTc1Y0alxkQkZHTOdDafVmdpx2XrBHM